name: sudoku
version: 0.1.3
author: Demis Bellot<demis.bellot@gmail.com>
description: A Sudoku solver for Dart
homepage: https://github.com/dartist/sudoku_solver

#dependencies:
#  unittest: any

dependencies:
  benchmark_harness: any